<?php // generated by Nette 
return array(
	'modules' => array(
		'googleanalytics' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'GoogleanalyticsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/googleanalytics-module',
			'autoload' => array(
				'psr-0' => array(
					'GoogleanalyticsModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'forms' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'FormsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/forms-module',
			'autoload' => array(
				'psr-0' => array(
					'FormsModule' => '',
				),
			),
			'require' => array(
				'assets' => '2.1.x',
			),
		),
		'blog' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'BlogModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/blog-module',
			'autoload' => array(
				'psr-0' => array(
					'BlogModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'translator' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'TranslatorModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/translator-module',
			'autoload' => array(
				'psr-0' => array(
					'TranslatorModule' => '',
				),
			),
			'require' => array(),
		),
		'assets' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'AssetsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/assets-module',
			'autoload' => array(
				'psr-0' => array(
					'AssetsModule' => '',
				),
			),
			'require' => array(),
		),
		'select2' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'Select2Module\\Module',
			'version' => '3.4.1',
			'path' => '%libsDir%/venne/select2-module',
			'autoload' => array(),
			'require' => array(),
		),
		'guestbook' => array(
			'status' => 'uninstalled',
			'action' => '',
			'class' => 'GuestbookModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/guestbook-module',
			'autoload' => array(
				'psr-0' => array(
					'GuestbookModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'dynatree' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'DynatreeModule\\Module',
			'version' => '1.2.4',
			'path' => '%libsDir%/venne/dynatree-module',
			'autoload' => array(),
			'require' => array(
				'jquery2.0' => 'x',
			),
		),
		'jquery2.0' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'JQueryModule\\Module',
			'version' => '2.0.0',
			'path' => '%libsDir%/venne/jquery2.0-module',
			'autoload' => array(),
			'require' => array(),
		),
		'ace' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'AceModule\\Module',
			'version' => '1.1.01',
			'path' => '%libsDir%/venne/ace-module',
			'autoload' => array(
				'psr-0' => array(
					'AceModule' => '',
				),
			),
			'require' => array(),
		),
		'bootstrap3' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'Bootstrap3Module\\Module',
			'version' => '3.0.2',
			'path' => '%libsDir%/venne/bootstrap3-module',
			'autoload' => array(),
			'require' => array(),
		),
		'doctrine' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'DoctrineModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/doctrine-module',
			'autoload' => array(
				'psr-0' => array(
					'DoctrineModule' => '',
				),
			),
			'require' => array(
				'forms' => '2.1.x',
			),
		),
		'mailform' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'MailformModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/mailform-module',
			'autoload' => array(
				'psr-0' => array(
					'MailformModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'gallery' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'GalleryModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/gallery-module',
			'autoload' => array(
				'psr-0' => array(
					'GalleryModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
				'blog' => '2.1.x',
			),
		),
		'ckeditor' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'CkeditorModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/ckeditor-module',
			'autoload' => array(
				'psr-0' => array(
					'CkeditorModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'jqueryui1.10' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'JQueryui1_10Module\\Module',
			'version' => '1.10.0',
			'path' => '%libsDir%/venne/jqueryui1.10-module',
			'autoload' => array(),
			'require' => array(),
		),
		'bootstrapmodal' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'BootstrapmodalModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/bootstrapmodal-module',
			'autoload' => array(),
			'require' => array(),
		),
		'typeahead' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'TypeaheadModule\\Module',
			'version' => '0.9.3',
			'path' => '%libsDir%/venne/typeahead-module',
			'autoload' => array(),
			'require' => array(
				'hogan' => '2.0.x',
			),
		),
		'cms' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'CmsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/cms-module',
			'autoload' => array(
				'psr-0' => array(
					'CmsModule' => '',
				),
				'files' => array(
					'static/autoload.php',
				),
			),
			'require' => array(
				'doctrine' => '2.1.x',
				'assets' => '2.1.x',
				'translator' => '2.1.x',
				'bootstrap3' => 'x',
				'bootstrapmodal' => '2.1.x',
				'jquery2.0' => 'x',
				'jqueryui1.10' => 'x',
				'select2' => '3.4.x',
				'typeahead' => '0.9.x',
				'dynatree' => '1.2.x',
				'stringtoslug' => '1.2.x',
				'holder' => '2.0.x',
				'bootstrapdatetime' => '0.0.x',
				'grido' => '2.0.x',
				'jqueryfileupload' => '8.8.x',
				'ajax' => '2.0.x',
			),
		),
		'stringtoslug' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'StringtoslugModule\\Module',
			'version' => '1.2.1',
			'path' => '%libsDir%/venne/stringtoslug-module',
			'autoload' => array(),
			'require' => array(),
		),
		'bootstrapdatetime' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'BootstrapdatetimeModule\\Module',
			'version' => '0.0.11',
			'path' => '%libsDir%/venne/bootstrapdatetime-module',
			'autoload' => array(),
			'require' => array(),
		),
		'importer' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'ImporterModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/importer-module',
			'autoload' => array(
				'psr-0' => array(
					'ImporterModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'holder' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'HolderModule\\Module',
			'version' => '2.0.0',
			'path' => '%libsDir%/venne/holder-module',
			'autoload' => array(),
			'require' => array(),
		),
		'hogan' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'HoganModule\\Module',
			'version' => '2.0.0',
			'path' => '%libsDir%/venne/hogan-module',
			'autoload' => array(),
			'require' => array(),
		),
		'lightbox' => array(
			'status' => 'uninstalled',
			'action' => '',
			'class' => 'LightboxModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/lightbox-module',
			'autoload' => array(
				'psr-0' => array(
					'LightboxModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'jqueryfileupload' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'JqueryfileuploadModule\\Module',
			'version' => '8.8.5',
			'path' => '%libsDir%/venne/jqueryfileupload-module',
			'autoload' => array(
				'classmap' => array(
					'src/UploadHandler.php',
				),
			),
			'require' => array(),
		),
		'grido' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'GridoModule\\Module',
			'version' => '2.0.0',
			'path' => '%libsDir%/venne/grido-module',
			'autoload' => array(),
			'require' => array(),
		),
		'ajax' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'AjaxModule\\Module',
			'version' => '2.0.0',
			'path' => '%libsDir%/venne/nette-ajax',
			'autoload' => array(
				'psr-0' => array(
					'VojtechDobes' => '',
				),
			),
			'require' => array(),
		),
		'site' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'SiteModule\\Module',
			'version' => '2.0.0',
			'path' => '%modulesDir%/site-module',
			'autoload' => array(
				'psr-0' => array(
					'SiteModule' => '',
				),
			),
			'require' => array(),
		),
		'deployment' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'DeploymentModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/deployment-module',
			'autoload' => array(
				'psr-0' => array(
					'DeploymentModule' => '',
				),
			),
			'require' => array(
				'doctrine' => '2.1.x',
			),
		),
		'events' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'EventsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/events-module',
			'autoload' => array(
				'psr-0' => array(
					'EventsModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
				'blog' => '2.1.x',
			),
		),
		'directory' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'DirectoryModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/directory-module',
			'autoload' => array(
				'psr-0' => array(
					'DirectoryModule' => '',
				),
			),
			'require' => array(
				'cms' => '2.1.x',
			),
		),
		'fio' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'FioModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/fio-module',
			'autoload' => array(
				'psr-0' => array(
					'FioModule' => '',
				),
			),
			'require' => array(
				'payments' => '2.1.x@dev',
			),
		),
		'payments' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'PaymentsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/payments-module',
			'autoload' => array(
				'psr-0' => array(
					'PaymentsModule' => '',
				),
			),
			'require' => array(
				'directory' => '2.1.x',
			),
		),
		array(
			'status' => 'uninstalled',
			'action' => '',
			'class' => 'SiteModule\\Module',
			'version' => NULL,
			'path' => '%modulesDir%/site-module',
			'autoload' => array(),
			'require' => array(),
		),
	),
);